baseURL = '//log.nosame.live/'
languageCode = 'zh-CN'
title = '平凡之路 | No Same'
theme = 'papermod'
copyright = '©2022 Martin Lee. 码钉的博客. 物我两相忘，寄情Coding间.'
env = 'production'
description = '"码钉的物我两相忘"'
keywords = 'Blog, Coding, Daily Life'
author = 'Martin Lee'
images = '[<link or path of image for opengraph, twitter-cards>]'
DateFormat = '2006-01-02 3:4 pm'
defaultTheme = 'auto'
ShowReadingTime = 'true'
ShowShareButtons = 'true'
ShowPostNavLinks = 'true'
ShowBreadCrumbs = 'true'
ShowCodeCopyButtons = 'true'
ShowWordCount = 'true'
ShowRssButtonInSectionTermList = 'true'
UseHugoToc = 'true'
disableSpecial1stPost = 'false'
disableScrollToTop = 'false'
comments = 'true'
hidemeta = 'false'
hideSummary = 'false'
showtoc = 'true'
tocopen = 'false'

[taxonomies]
tag = 'tags'
category = 'categories'

[menu]
[[menu.main]]
identifier = 'categories'
name = 'categories'
url = '/categories/'
weight = '10'
[[menu.main]]
identifier = 'tags'
name = 'tags'
url = '/tags/'
weight = '20'
[[menu.main]]
identifier = 'example'
name = 'example.org'
url = 'https://example.org'
weight = '30'
