baseURL = '//log.nosame.live/'
languageCode = 'zh'
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
title = '平凡之路'
theme = 'fixit'
summaryLength = 140

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
    # 向菜单项添加用户定义的内容
    [menu.main.params]
      # 添加 CSS 类到菜单项
      class = ""
      # 是否为草稿菜单，类似草稿页面
      draft = false
      # 添加 fontawesome 图标到菜单项
      icon = "fa-solid fa-archive"
      # 设置菜单项类型，可选值：["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"

[params]
  # FixIt 0.2.15 | 更改 FixIt 主题版本
  version = "0.2.X" # 例如："0.2.X", "0.2.15", "v0.2.15" 等
  # 网站描述
  description = "码钉的博客."
  # 网站关键词
  keywords = ["码钉", "nosame.net", "天下无双", "平凡之路"]
  # 网站默认主题样式 ["light", "dark", "auto"]
  defaultTheme = "auto"
  # FixIt 0.2.0 | 新增 日期格式
  dateFormat = "2006-01-02"
  # 网站图片，用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
  # FixIt 0.2.12 | 新增 开启 PWA 支持
  enablePWA = true
  # FixIt 0.2.14 | 新增 是否自动显示外链图标
  externalIcon = false
  # FixIt 0.2.14 | 新增 默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记
  # 您可以将其关闭，但如果您不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法
  disableThemeInject = false

  # FixIt 0.2.0 | 新增 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
    title = "平凡之路"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"
    # FixIt 0.2.12 | 更改 Android 浏览器主题色
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  # FixIt 0.2.0 | 新增 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # FixIt 0.2.1 | 新增 最大结果数目
    maxResultLength = 10
    # FixIt 0.2.3 | 新增 结果内容片段长度
    snippetLength = 50
    # FixIt 0.2.1 | 新增 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # FixIt 0.2.4 | 新增 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # 页面头部导航栏配置
  [params.header]
    # FixIt 0.2.13 | 更改 桌面端导航栏模式 ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | 更改 移动端导航栏模式 ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # FixIt 0.2.0 | 新增 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/logo.png"
      # 标题名称
      name = "平凡之路"
      # FixIt 0.2.5 | 新增 是否为标题显示打字机动画
      typeit = false
    # FixIt 0.2.12 | 新增 页面头部导航栏副标题配置
    [params.header.subtitle]
      # 副标题名称
      name = "Normalized Pathway"
      # 是否为副标题显示打字机动画
      typeit = true

  # 页面底部信息配置
  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2009
    wordCount = true
    license = '码钉的博客. 物我两相忘，寄情Coding间.'

  # FixIt 0.2.0 | 新增 Section（所有文章）页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
    # FixIt 0.2.13 | 新增 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # FixIt 0.2.0 | 新增 List（目录或标签）页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 主页配置
  [params.home]
    # FixIt 0.2.0 | 新增 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = false
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6

  # FixIt 0.2.0 | 更改 文章页面配置
  [params.page]
    # FixIt 0.2.0 | 新增 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FixIt 0.2.0 | 新增 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FixIt 0.2.0 | 新增 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # FixIt 0.2.0 | 新增 是否使用 ruby 扩展语法
    ruby = true
    # FixIt 0.2.0 | 新增 是否使用 fraction 扩展语法
    fraction = true
    # FixIt 0.2.0 | 新增 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 许可协议信息（支持 HTML 格式）
    license = '转载请引用本页，商用须请求授权'
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false
    # FixIt 0.2.4 | 新增 是否在 RSS 中显示全文内容
    rssFullText = false
    # FixIt 0.2.13 | 新增 页面样式 ["narrow", "normal", "wide", ...]
    pageStyle = "narrow"
    # FixIt 0.2.14 | 新增 强制使用 Gravatar 作为作者头像
    gravatarForce = false
    # FixIt 0.2.17 | 更改 开启自动书签支持
    # 如果为 true，则在关闭页面时保存阅读进度
    autoBookmark = false
    # FixIt 0.2.17 | 新增 是否使用 字数统计
    wordCount = true
    # FixIt 0.2.17 | 新增 是否使用 预计阅读
    readingTime = true
    # FixIt 0.2.17 | 新增 文章结束标志
    endFlag = "㊡"

    # FixIt 0.2.15 | 新增 转载配置
    [params.page.repost]
      enable = false
      url = ""
    # FixIt 0.2.0 | 新增 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
    # FixIt 0.2.0 | 新增 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # FixIt 0.2.13 | 新增 是否显示代码块的编辑按钮
      edit = false
      # 默认展开显示的代码行数
      maxShownLines = 10
    # FixIt 0.2.17 | 新增 赞赏设置
    [params.page.reward]
      enable = false
      animation = false
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "after"
      # comment = "Buy me a coffee"
      [params.page.reward.ways]
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
    # FixIt 0.2.0 | 更改 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Weibo = true
      Baidu = true
    # FixIt 0.2.15 | 更改 评论系统设置
    
    # FixIt 0.2.7 | 新增 第三方库配置
    [params.page.comment]
      enable = true
      # FixIt 0.2.14 | 新增 Giscus 评论系统设置
      [params.page.comment.giscus]
        enable = true
        repo = "freshwind2004/nosame.live"
        repoId = "R_kgDOIM0fPw"
        category = "Comments"
        categoryId = "DIC_kwDOIM0fP84CSODg"
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top" # top, bottom
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""


  # FixIt 0.2.7 | 新增 Cookie 许可配置
  [params.cookieconsent]
    enable = false

  # FixIt 0.2.16 | 新增 返回顶部
  [params.backToTop]
    enable = true
    # 在 b2t 按钮中显示滚动百分比
    scrollpercent = false

  # FixIt 0.2.16 | 新增 阅读进度条
  [params.readingProgress]
    enable = false
    # 可用值：["left", "right"]
    start = "left"
    # 可用值：["top", "bottom"]
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ################## 必要的配置 ##################
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false 
    ################## 必要的配置 ##################
    guessSyntax = true
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "Martin Lee"
  email = "info@nosame.live"
  link = "https://log.nosame.live/"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# FixIt 0.2.15 | 更改
[outputFormats]
  # 用于输出 Markdown 格式文档的设置
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.2.15 | 新增 用于输出 baidu_urls.txt 文件的设置
  [outputFormats.BaiduUrls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# FixIt 0.2.15 | 更改 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON", "BaiduUrls"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
