baseURL = '//log.nosame.live/'
languageCode = 'zh'
hasCJKLanguage = true
title = '平凡之路 | Normalized Pathway'
theme = 'papermod'
copyright = '©2022 Martin Lee. 码钉的博客. 物我两相忘，寄情Coding间.'
enableEmoji = true

[params]
  author = 'Martin Lee'
  env = 'production'
  DateFormat = '2006-01-02 3:4 pm'
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  showtoc = true
  comments = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[[menu.main]]
  identifier = 'categories'
  name = '分类'
  url = '/categories/'
  weight = 10

[[menu.main]]
  identifier = 'tags'
  name = '标签'
  url = '/tags/'
  weight = 20

[[menu.main]]
  identifier = 'duckduckgo'
  name = '搜索'
  url = 'https://duckduckgo.com'
  weight = 30
