# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Rebuild Hugo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.3'

    - name: Build
      run:
        hugo --minify
        
    - uses: actions/deploy-pages@v1
